### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by kaoz70** [atticoos/titanium-chromecast#5]
Hello, I would like to know what the status of this project is? I'm particularly curious about the Video Casting capabilities in the current state of the project.

Regards,
Miguel

**Comment by atticoos** [comment]
Hey @kaoz70, this project is currently in a bit of limbo. I'm no longer using Appcelerator these days, so I'm not actively contributing. I'll update the README to note that I'm looking for contributors to join the project.

As for capabilities, the [feature/media-casting](https://github.com/ajwhite/titanium-chromecast/tree/feature/media-casting) branch should work for basic video casting.

**Comment by kaoz70** [comment]
Alright, thanks for the update, I'll check the branch and see if its possible to use it in our project.
