### ISSUE TITLE
GCKDeviceManager must be called on main thread error

### ISSUE THREAD

**Issue by TylerZubke** [atticoos/titanium-chromecast#6]
I get this error roughly 50% of the time 

**\* Assertion failure in -[GCKDeviceManager launchApplication:withLaunchOptions:], /Volumes/BuildData/pulse-data/agents/wpyl21.hot/recipes/624509338/base/google3/googlemac/iPhone/Chromecast/SDK/Framework/Classes/GCKDeviceManager.m:629
[GCKDeviceManager launchApplication:withLaunchOptions:] must be called on main thread

Again, it doesn't happen every time. My javascript is almost identical to what you provide on your blog. Any ideas?

**Comment by TylerZubke** [comment]
Nevermind, ENSURE_UI_THREAD_0_ARGS took care of it.

**Comment by atticoos** [comment]
If you'd like to create a PR, I'd welcome that fix! 

Glad you got that working 👍
